default_language_version:
  python: /usr/local/bin/python

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        args:
          - --exclude=.+/migrations/
          - --max-line-length=88
          - --ignore=E501
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]

